export default [
  {
    "name": "Alpha Arbutin 2% + HA",
    "price": "8.90",
    "image": "/assets/rdn-alpha-arbutin-2pct-ha-30ml.png",
    "contraindications": [],
    "category": ["Serums"],
    "desc": "A concentrated serum with pure alpha arbutin and hyaluronic acid"
  },
  {
    "name": "Mineral UV Filters SPF 15 with Antioxidants",
    "price": "8.90",
    "image": "/assets/rdn-mineral-uv-filters-spf-15-with-antioxidants-50ml.png",
    "contraindications": [],
    "category": [],
  },
  {
    "name": "Ascorbic Acid 8% + Alpha Arbutin 2%",
    "price": "10.00",
    "image": "/assets/rdn-100pct-AscorbicAcid8+AlphaArbutin2-Product-30ml.png",
    "contraindications": [],
    "category": ["Vitamin C", "Serums"],
    "desc": "Broad Spectrum SPF 15 UVA/UVB Protection"
  }, {
    "name": "Retinol 0.5% in Squalane",
    "price": "5.80",
    "image": "/assets/rdn-retinol-0-5pct-in-squalane-30ml.png",
    "contraindications": ["Retinoids", "Direct Acids", "Vitamin C"],
    "category": ["Retinoids", "Serums"],
    "desc": "Highly-Stable, Water-Free Solution of 0.5% Pure Retinol"
  }, {
    "name": "The Balance Set",
    "price": "29.00",
    "image": "/assets/rdn-balance-set.png",
    "category": ["set"],
    "contraindications": [],
    "desc": "A set for balance"
  }, {
    "name": "100% Cold-Pressed Virgin Marula Oil",
    "price": "9.90",
    "image": "/assets/rdn-100pct-cold-pressed-virgin-marula-oil-30ml.png",
    "contraindications": [],
    "category": [],
    "desc": "Daily support formula for hair and skin"
  },
  {
    "name": "100% Plant-Derived Squalane",
    "price": "7.90",
    "image": "/assets/rdn-100pct-plant-derived-squalane-30ml.png",
    "contraindications": [],
    "category": ["Serums"],
    "desc": "A lightweight plant-derived solution to support healthy hydration"
  },
  {
    "name": "100% Plant-Derived Hemi-Squalane",
    "price": "3.95",
    "image": "/assets/rdn-100pct-plant-derived-hemi-squalane-30ml.png",
    "contraindications": [],
    "category": ["Serums"],
    "desc": "A Fast-Absorbing, Non-Greasy Hydration Solution for Skin and Hair"
  },
  {
    "name": "100% Organic Virgin Sea-Buckthorn Fruit Oil",
    "price": "14.90",
    "image": "/assets/rdn-100pct-Organic-Virgin-Sea-Buckthorn-Fruit-Oil.png",
    "contraindications": [],
    "category": ["Oils and Moisturizers"],
    "desc": "Daily Support Formula for All Skin Types"
  },
  {
    "name": "'B' Oil",
    "price": "9.20",
    "image": "/assets/rdn-b-oil-30ml.png",
    "contraindications": [],
    "category": ["Oils and Moisturizers"],
    "desc": "Daily Support Formula for All Skin Types"
  },
  {
    "name": "100% Niacinamide Powder",
    "price": "5.80",
    "image": "/assets/rdn-100pct-niacinamide-powder-20g.png",
    "contraindications": ["Vitamin C", "Direct Acids"],
    "category": ["Serums"],
    "desc": "Less than 100ppm residual Nicotinic Acid"
  },
  {
    "name": "Argireline Solution 10%",
    "price": "7.90",
    "image": "/assets/rdn-argireline-solution-10pct-30ml.png",
    "contraindications": ["Vitamin C", "Direct Acids"],
    "category": ["Serums", "Peptides"],
    "desc": "Lightweight serum with 10 % argireline peptide complex"
  },
  {
    "name": "Dropper - 1pc",
    "price": ".90",
    "image": "/assets/rdn-dropper.png",
    "contraindications": [],
    "category": ["Accessories"],
    "desc": "For Serum Foundations An optional dropper to help dispense serum foundations. Suitable for 30ml Serum Foundation bottles."
  },
  {
    "name": "EUK 134 0.1%",
    "price": "8.80",
    "image": "/assets/rdn-euk-134-0-1pct-30ml.png",
    "contraindications": ["Direct Acids", "Vitamin C", "Resveratrol 3% + Ferulic Acid 3%",],
    "category": ["Serums"],
    "desc": "Water-Free, High-Potency Antioxidant Formula",
  },
  {
    "name": "Marine Hyaluronics",
    "price": "6.80",
    "image": "/assets/rdn-marine-hyaluronics-30ml.png",
    "contraindications": [],
    "category": ["Serums"],
    "desc": "Ultra-Lightweight Hydration Support with Marine-Derived Vegan Water Reservoirs",
  },
  {
    "name": "100% Organic Virgin Chia Seed Oil",
    "price": "7.70",
    "image": "/assets/rdn-100pct-organic-virgin-chia-seed-oil-30ml.png",
    "contraindications": [],
    "category": ["Oils and Moisturizers"],
    "desc": "Daily Support Formula for All Skin Types",
  },
  {
    "name": "Amino Acids + B5",
    "price": "6.80",
    "image": "/assets/rdn-amino-acids-b5-30ml.png",
    "contraindications": [],
    "category": ["Serums"],
    "desc": "A Concentrated Hydration Support Formula",
  },
  {
    "name": "Resveratrol 3% + Ferulic Acid 3%",
    "price": "7.90",
    "image": "/assets/rdn-resveratrol-3pct-ferulic-acid-3pct-30ml.png",
    "contraindications": ["EUK 134 0.1%"],
    "category": ["Serums"],
    "desc": "Water-Free, High-Potency Antioxidant Formula",
  },
  {
    "name": "100% Organic Cold-Pressed Rose Hip Seed Oil",
    "price": "9.80",
    "image": "/assets/rdn-100pct-organic-cold-pressed-rose-hip-seed-oil-30ml.png",
    "contraindications": [],
    "category": ["Oils and Moisturizers"],
    "desc": "Daily support formula for all skin types",
  },
  {
    "name": "Lactic Acid 5% + HA",
    "price": "6.50",
    "image": "/assets/rdn-lactic-acid-5pct-ha-30ml.png",
    "contraindications": ["Direct Acids", "Peptides", "Retinoids", "Vitamin C", "100% Niacinamide Powder", "EUK 134 0.1%"],
    "category": ["Direct Acids"],
    "desc": "A mild lactic acid superficial peeling formulation",
  },
  {
    "name": "The Daily Set",
    "price": "19.00",
    "image": "/assets/rdn-daily-set.png",
    "contraindications": [],
    "category": ["Set"],
    "desc": "An everyday set",
  },
  {
    "name": "Retinol 1% in Squalane",
    "price": "6.70",
    "image": "/assets/rdn-retinol-1pct-in-squalane-30ml.png",
    "contraindications": ["Retinoids", "Direct Acids", "Vitamin C"],
    "category": ["Retinoids", "Serums"],
    "desc": "Highly-Stable, Water-Free Solution of 1% Pure Retinol",
  },
  {
    "name": "Buffet",
    "price": "14.80",
    "image": "/assets/rdn-buffet-30ml.png",
    "contraindications": ["Vitamin C", "Direct Acids"],
    "category": ["Peptides"],
    "desc": "Multi-technology peptide serum",
  },
  {
    "name": "Retinol 0.2% in Squalane",
    "price": "5.30",
    "image": "/assets/rdn-retinol-0-2pct-in-squalane-30ml.png",
    "contraindications": ["Retinoids", "Direct Acids", "Vitamin C"],
    "category": ["Retinoids", "Serums"],
    "desc": "Highly-Stable, Water-Free Solution of 0.2% Pure Retinol",
  },
  {
    "name": "Vitamin C Suspension 30% in Silicone",
    "price": "6.80",
    "image": "/assets/rdn-vitamin-c-suspension-30pct-in-silicone-30ml.png",
    "contraindications": ["Niacinamide", "Direct Acids", "Retinoids", "EUK 134 0.1%"],
    "category": ["Vitamin C"],
    "desc": "A Water-Free, Stable Suspension of 30% Pure L-Ascorbic Acid in Light Silicones",
  },
  {
    "name": "Ascorbyl Tetraisopalmitate Solution 20% in Vitamin F",
    "price": "17.80",
    "image": "/assets/rdn-ascorbyl-tetraisopalmitate-solution-20pct-in-vitamin-f-30ml.png",
    "contraindications": ["Niacinamide"],
    "category": ["Vitamin C"],
    "desc": "High-strength oil-solubilized vitamin C derivative in vitamin F",
  },
  {
    "name": "Ascorbyl Glucoside Solution 12%",
    "price": "17.80",
    "image": "/assets/rdn-ascorbyl-glucoside-solution-12pct-30ml.png",
    "contraindications": ["Niacinamide"],
    "category": ["Niacinamide", "Vitamin C"],
    "desc": "A brightening serum with stabilized vitamin C derivative",
  },
  {
    "name": "Caffeine Solution 5% + EGCG",
    "price": "6.70",
    "image": "/assets/rdn-caffeine-solution-5pct-egcg-30ml.png",
    "contraindications": [],
    "category": ["Serums"],
    "desc": "Reduces appearance of eye contour pigmentation and of puffiness",
  },
  {
    "name": "100% L-Ascorbic Acid Powder",
    "price": "5.80",
    "image": "/assets/rdn-100pct-l-ascorbic-acid-powder-20g.png",
    "contraindications": ["Niacinamide", "Peptides", "Direct Acids", "Retinoids", "EUK 134 0.1%"],
    "category": ["Vitamin C"],
    "desc": "Fine 325 Mesh Topical Powder",
  },
  {
    "name": "100% Organic Cold-Pressed Borage Seed Oil",
    "price": "4.20",
    "image": "/assets/rdn-100pct-cold-pressed-borage-seed-oil-30ml.png",
    "contraindications": [],
    "category": ["Oils and Moisturizers"],
    "desc": "Daily Support Formula for All Skin Types . Daily Support Formula for All Skin Types.",
  },
  {
    "name": "Lactic Acid 10% + HA",
    "price": "6.80",
    "image": "/assets/rdn-lactic-acid-10pct-ha-30ml.png",
    "contraindications": ["Direct Acids", "Peptides", "Retinoids", "Vitamin C", "100% Niacinamide Powder", "EUK 134 0.1%"],
    "category": ["Direct Acids"],
    "desc": "A high-strength lactic acid superficial peeling formulation",
  },
  {
    "name": "Magnesium Ascorbyl Phosphate 10%",
    "price": "9.60",
    "image": "/assets/rdn-magnesium-ascorbyl-phosphate-10pct-30ml.png",
    "contraindications": ["Niacinamide"],
    "category": ["Serums", "Vitamin C"],
    "desc": "A brightening hydrator with stabilized vitamin C derivative",
  },
  {
    "name": "Azelaic Acid Suspension 10%",
    "price": "7.90",
    "image": "/assets/rdn-azelaic-acid-suspension-10pct-30ml.png",
    "contraindications": [],
    "category": ["Serums", "Direct Acids"],
    "desc": "Multifunctional brightening formula",
  },
  {
    "name": "The No-Brainer Set",
    "price": "29.00",
    "image": "/assets/rdn-no-brainer-set.png",
    "contraindications": [],
    "category": ["set"],
    "desc": "A no-brainer",
  },
  {
    "name": "Granactive Retinoid 2% in Squalane",
    "price": "9.60",
    "image": "/assets/rdn-granactive-retinoid-5pct-in-squalane-30ml.png",
    "contraindications": ["Retinoids", "Direct Acids", "Vitamin C"],
    "category": ["Retinoids", "Serums"],
    "desc": "Highly-Stable, Water-Free Solution of 0.5% Ester of All-Trans Retinoic Acid",
  },
  {
    "name": "Salicylic Acid 2% Solution",
    "price": "5.30",
    "image": "/assets/rdn-salicylic-acid-2pct-solution-30ml.png",
    "contraindications": ["Direct Acids", "Peptides", "Retinoids", "Vitamin C", "100% Niacinamide Powder", "EUK 134 0.1%"],
    "category": ["Direct Acids"],
    "desc": "With 2% salicylic acid and witch hazel",
  },
  {
    "name": "AHA 30% + BHA 2% Peeling Solution",
    "price": "7.20",
    "image": "/assets/rdn-aha-30pct-bha-2pct-peeling-solution-30ml.png",
    "contraindications": ["Direct Acids", "Peptides", "Retinoids", "Vitamin C", "100% Niacinamide Powder", "EUK 134 0.1%"],
    "category": ["Direct Acids"],
    "desc": "With 30% alpha hydroxy acids (glycolic/lactic/tartaric/citric), 2% beta hydroxy acid (salicylic acid), hyaluronic acid crosspolymer, vitamin b5, black carrot and tasmanian pepperberry",
  },
  {
    "name": "Granactive Retinoid 2% Emulsion (Previously Advanced Retinoid 2%)",
    "price": "9.80",
    "image": "/assets/rdn-granactive-retinoid-2pct-in-squalane-30ml.png",
    "contraindications": ["Retinoids", "Direct Acids", "Vitamin C"],
    "category": ["Retinoids"],
    "desc": "Previously Advanced Retinoid 2%",
  },
  {
    "name": "Salicylic Acid 2% Masque",
    "price": "12.00",
    "image": "/assets/rdn-salicylic-acid-2pct-masque-50ml.png",
    "contraindications": ["Direct Acids", "Peptides", "Retinoids", "Vitamin C", "100% Niacinamide Powder", "EUK 134 0.1%"],
    "category": ["Direct Acids"],
    "desc": "With 2% Salicylic Acid, Vegetable Charcoal, Amazonian Clays and Squalane",
  },

  {
    "name": "Squalane Cleanser",
    "price": "7.90",
    "image": "/assets/rdn-squalane-cleanser-50ml.png",
    "contraindications": [],
    "category": ["Cleansers"],
    "desc": "A Gentle, Moisturizing Facial Cleanser",
  },

  {
    "name": "Matrixyl 10% + HA",
    "price": "11.50",
    "image": "/assets/rdn-matrixyl-10pct-ha-30ml.png",
    "contraindications": ["Vitamin C", "Direct Acids"],
    "category": ["Peptides"],
    "desc": "A high-strength peptide formulation",
  },
  {
    "name": "Natural Moisturizing Factors + HA",
    "price": "5.80",
    "image": "/assets/rdn-natural-moisturizing-factors-ha-30ml.png",
    "contraindications": ["Moisturizers"],
    "category": ["Oils and Moisturizers"],
    "desc": "Surface hydration formula",
  },
  {
    "name": "100% Organic Cold-Pressed Moroccan Argan Oil",
    "price": "6.80",
    "image": "/assets/rdn-100pct-organic-cold-pressed-moroccan-argan-oil-30ml.png",
    "contraindications": [],
    "category": ["Oils and Moisturizers"],
    "desc": "Daily support formula for hair and skin",
  },
]
